version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: expense
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: expense
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy