spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/expense
    username: expense
    password: expense
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64}