name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn -q -B -f expense-platform-portfolio/pom.xml clean verify
      - name: Upload JaCoCo aggregate report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-aggregate
          path: expense-platform-portfolio/target/site/jacoco-aggregate/